# Generated by Django 4.2.3 on 2023-07-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_ciudad", models.CharField(max_length=30)),
                ("descripcion_ciudad", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=30)),
                ("nit", models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tipo", models.CharField(max_length=30)),
                ("descripcion_tipo", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("documento", models.IntegerField(max_length=10)),
                ("fecha_nacimiento", models.DateField(null=True)),
                ("email", models.EmailField(max_length=50)),
                ("telefono", models.IntegerField(max_length=10)),
                ("usuario", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.empresa"
                    ),
                ),
                (
                    "lugar_residencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.ciudad"
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.tipodocumento",
                    ),
                ),
            ],
        ),
    ]
