# Generated by Django 4.2.3 on 2023-07-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_empleado_documento_alter_empleado_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa", name="nit", field=models.IntegerField(),
        ),
    ]
