# Generated by Django 4.2.3 on 2023-07-13 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_empresa_nit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empleado", old_name="last_name", new_name="apellido",
        ),
        migrations.RenameField(
            model_name="empleado", old_name="first_name", new_name="nombre",
        ),
        migrations.AlterField(
            model_name="empleado",
            name="fecha_nacimiento",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
