# Generated by Django 4.2.3 on 2023-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_last_name_empleado_apellido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado", name="documento", field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="empleado", name="telefono", field=models.BigIntegerField(),
        ),
    ]
