# Generated by Django 4.2.3 on 2023-07-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_empleado_documento_alter_empleado_telefono"),
    ]

    operations = [
        migrations.RemoveField(model_name="ciudad", name="descripcion_ciudad",),
        migrations.RemoveField(model_name="tipodocumento", name="descripcion_tipo",),
    ]
