# Generated by Django 4.2.3 on 2023-07-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_remove_empresa_id_remove_tipodocumento_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="ciudad", name="id",),
        migrations.AlterField(
            model_name="ciudad",
            name="nombre_ciudad",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
