# Generated by Django 4.2.3 on 2023-07-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_ciudad_nombre_ciudad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="id",
            field=models.IntegerField(
                auto_created=True, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
